eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

spring:
    cloud:
      config:
        uri: http://localhost:8080
      server:
        git:
          uri: http://localhost:8080
