eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

cart:
  service:
    name: cart-service-2
    
spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    cloud:
      config:
        uri: https://github.com/Elouaret/config-repo.git
        server:
          git:
            uri: https://github.com/Elouaret/config-repo.git
            force-pull: true
            searchPaths: '\{application}'
            clone-on-start: true
            default-label: main
            refresh-rate: 1
    compatibility-verifier:
      enabled: false
