eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

spring:
    cloud:
      config:
        uri: https://github.com/Elouaret/config-repo.git
        server:
          git:
            #searchpaths: {application}/{profile}
            clone-on-start: true
            default-label: main
    compatibility-verifier:
      enabled: false
