server:
  port: ${random.int(8100,8199)}

user:
  role: dev-role2
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG 
   
spring:
    cloud:
      config:
        uri: http://localhost:8081
