server:
  port: 8090  
  # port: ${random.int(8081,8099)}

cart:
  service:
    name: cart-service

item:
  service:
    name: item-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: cart-service
          uri: http://localhost:8100/
          predicates:
            - Path=/cart/**
        - id: item-service
          uri: http://localhost:8200/
          predicates:
            - Path=/item/**
    
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
