server:
  port: 8090  
  # port: ${random.int(8081,8099)}

cart:
  service:
    name: cart-service

item:
  service:
    name: item-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
          lowerCaseServiceId: true
      mvc:
        routes:
          - id: ${cart.service.name}
            uri: lb://${cart.service.name}
            predicates:
              - Path=/**
          - id: ${item.service.name}
            uri: lb://${item.service.name}
            predicates:
              - Path=/**    
      routes[0]:
        id: item-service
        uri: lb://item-service
        predicates[0]: Path=/
      routes[1]:
        id: cart-service
        uri: lb://cart-service
        predicates[0]: Path=/  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true

